on: push
name: Publish Angular App
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache and modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm install
          npm run build
      #- name: Push to FB
        #uses: FirebaseExtended/action-hosting-deploy@v0
        #with:
          #repoToken: '${{ secrets.SWaver_workflow_token }}'
          #firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWAVER_LAB }}'
          #channelId: live
          #projectId: swaver-lab
